# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeiBo' do

  use_frameworks!

  pod 'AFNetworking'
  pod 'SDWebImage', '~>3.8.1'
  pod 'YYModel'
  pod 'MJRefresh'
  pod 'pop'
  pod 'SVProgressHUD'
  pod 'FMDB'
  pod 'SnapKit'
  pod 'HandyJSON'
  pod 'YYWebImage'
end
